
#ifndef DOCATTR_H
#define DOCATTR_H

#define DOC_UNKNOWN			_T("document")

#define DOC_ARCH			_T("archive")
#define DOC_ARCH_CATALOG	_T("catalog")
#define DOC_ARCH_DOCUMENT	_T("document")

#define DOC_TASK			_T("task")
#define DOC_TASK_SCHEDULE	_T("schedule")
#define DOC_TASK_STEP		_T("step")

#define DOC_SOAP				_T("Envelope")
#define DOC_SOAP_HEAD			_T("Header")
#define DOC_SOAP_BODY			_T("Body")
#define DOC_SOAP_ARRAY_ITEM		_T("item")
#define DOC_SOAP_FAULT			_T("Fault")
#define DOC_SOAP_FAULT_CODE		_T("faultcode")
#define DOC_SOAP_FAULT_STRING	_T("faultstring")

#define DOC_NOTES				_T("notes")

#define DOC_JSON				_T("rowset")

#define DOC_XML					_T("xml")
#define XML_ATTR_VERSION		_T("version")
#define XML_ATTR_ENCODING		_T("encoding")

#define DEF_XML_ENCODING			_T("utf-8")
#define DEF_XML_VERSION				_T("1.0")

#define DOC_SVG					_T("svg")
#define DOC_SVG_G				_T("g")

#define DOC_PATH				_T("path")
#define DOC_PATH_MOVE			_T("move")
#define DOC_PATH_LINE			_T("line")
#define DOC_PATH_ARC			_T("arc")
#define DOC_PATH_BEZIER			_T("bezier")

#define DOC_HTML				_T("html")
#define DOC_HTML_HEAD			_T("head")
#define DOC_HTML_TITLE			_T("title")
#define DOC_HTML_BODY			_T("body")

#define DOC_META				_T("meta")
#define DOC_META_HEAD			_T("head")
#define DOC_META_TITLE			_T("title")
#define DOC_META_META			_T("meta")
#define DOC_META_BODY			_T("body")

#define DOC_WSDL					_T("definitions")
#define DOC_WSDL_TYPES				_T("types")
#define DOC_WSDL_MESSAGE			_T("message")
#define DOC_WSDL_PORTTYPE			_T("portType")
#define DOC_WSDL_BINDING			_T("binding")
#define DOC_WSDL_SERVICE			_T("service")


#define DOC_SVC						_T("svc")
#define DOC_SVC_DECLARE				_T("declare")
#define DOC_SVC_DECLARE_INTERFACE	_T("interface")
#define DOC_SVC_DECLARE_VERSION		_T("version")
#define DOC_SVC_DECLARE_LICENSE		_T("license")
#define DOC_SVC_DECLARE_APPLICATION	_T("application")
#define DOC_SVC_MESSAGE				_T("message")
#define DOC_SVC_MESSAGE_FAULTCODE	_T("fault-code")
#define DOC_SVC_MESSAGE_FAULTSTRING	_T("fault-string")
#define DOC_SVC_CONTEXT				_T("context")
#define DOC_SVC_CONTEXT_SERVICE		_T("service")
#define DOC_SVC_CONTEXT_CLIENT		_T("client")
#define DOC_SVC_PACKAGE				_T("package")

#define DOC_PLOT					_T("plot")
#define DOC_PLOT_WIDTH				_T("width")
#define DOC_PLOT_HEIGHT				_T("height")
#define DOC_PLOT_RULER				_T("ruler")
#define DOC_PLOT_TYPE				_T("type")
#define DOC_PLOT_STYLE				_T("style")
#define DOC_PLOT_Y_GRADES			_T("y-grades")
#define DOC_PLOT_Y_GRADE			_T("y-grade")
#define DOC_PLOT_Y_STAGES			_T("y-stages")
#define DOC_PLOT_Y_STAGE			_T("y-stage")
#define DOC_PLOT_Y_BASES			_T("y-bases")
#define DOC_PLOT_Y_BASE				_T("y-base")
#define DOC_PLOT_Y_STEPS			_T("y-steps")
#define DOC_PLOT_Y_STEP				_T("y-step")
#define DOC_PLOT_Y_LABELS			_T("y-labels")
#define DOC_PLOT_Y_LABEL			_T("y-label")
#define DOC_PLOT_Y_COLORS			_T("y-colors")
#define DOC_PLOT_Y_COLOR			_T("y-color")
#define DOC_PLOT_Y_SHAPES			_T("y-shapes")
#define DOC_PLOT_Y_SHAPE			_T("y-shape")
#define DOC_PLOT_X_LABELS			_T("x-labels")
#define DOC_PLOT_X_LABEL			_T("x-label")
#define DOC_PLOT_X_COLORS			_T("x-colors")
#define DOC_PLOT_X_COLOR			_T("x-color")

#define DOC_MATRIX					_T("matrix")
#define DOC_MATRIX_ROWS				_T("rows")
#define DOC_MATRIX_COLS				_T("cols")
#define DOC_MATRIX_DATA				_T("data")

#define DOC_VECTOR					_T("vector")
#define DOC_VECTOR_SIZE				_T("size")
#define DOC_VECTOR_DIMENS			_T("dimens")
#define DOC_VECTOR_DATA				_T("data")

#define DOC_SCHEMA					_T("schema")
#define DOC_SCHEMA_ELEMENT			_T("element")
#define DOC_SCHEMA_ATTRIBUTE		_T("attribute")
#define DOC_SCHEMA_DECLARE			_T("declare")

#define DOC_FUNC				_T("func")
#define DOC_FUNC_PARAM			_T("param")

#define DOC_FRAMESET			_T("frameset")
#define DOC_FRAME				_T("frame")

#define DOC_FORM				_T("form")
#define DOC_FORM_SHAPE			_T("shape-field")
#define DOC_FORM_TEXT			_T("text-field")
#define DOC_FORM_RICH			_T("rich-field")
#define DOC_FORM_TAG			_T("tag-field")
#define DOC_FORM_MEMO			_T("memo-field")
#define DOC_FORM_LABEL			_T("label-field")
#define DOC_FORM_CODE			_T("code-field")
#define DOC_FORM_PHOTO			_T("photo-field")
#define DOC_FORM_HREF			_T("href-field")
#define DOC_FORM_CHECK			_T("check-field")
#define DOC_FORM_TABLE			_T("table-field")
#define DOC_FORM_GRID			_T("grid-field")
#define DOC_FORM_STATIS			_T("statis-field")
#define DOC_FORM_FORM			_T("form-field")
#define DOC_FORM_PLOT			_T("plot-field")
#define DOC_FORM_IMAGES			_T("images-field")
#define DOC_FORM_PAGENUM		_T("pagenum-field")

#define DOC_DIAGRAM				_T("diagram")
#define DOC_DIAGRAM_PROCESS		_T("process")
#define DOC_DIAGRAM_DOCUMENT	_T("document")
#define DOC_DIAGRAM_SHEET		_T("sheet")
#define DOC_DIAGRAM_JUDGE		_T("judge")
#define DOC_DIAGRAM_JOINT		_T("joint")

#define DOC_GRID				_T("grid")
#define DOC_GRID_COLSET			_T("colset")
#define DOC_GRID_ROWSET			_T("rowset")
#define DOC_GRID_COL			_T("col")
#define DOC_GRID_ROW			_T("row")

#define DOC_PROPER				_T("proper")
#define DOC_PROPER_SECTION		_T("section")
#define DOC_PROPER_ENTITY		_T("entity")

#define DOC_TREE				_T("tree")
#define DOC_TREE_ITEM			_T("item")

#define DOC_SPLIT				_T("split")
#define DOC_SPLIT_ITEM			_T("item")

#define DOC_MENU				_T("menu")
#define DOC_MENU_ITEM			_T("item")

#define DOC_TOOL				_T("tool")
#define DOC_TOOL_GROUP			_T("group")
#define DOC_TOOL_ITEM			_T("item")

#define DOC_TITLE				_T("title")
#define DOC_TITLE_ITEM			_T("item")

#define DOC_STATUS				_T("status")
#define DOC_STATUS_ITEM			_T("item")

#define DOC_LIST				_T("list")
#define DOC_LIST_ITEM			_T("item")
#define DOC_LIST_FILE			_T("file")
#define DOC_LIST_DIRECTORY		_T("directory")

#define DOC_LABEL				_T("label")
#define DOC_LABEL_ITEM			_T("item")

#define DOC_ANNO				_T("annotation")
#define DOC_ANNO_SPOT			_T("spot")

#define DOC_TOPOG				_T("topograph")
#define DOC_TOPOG_SPOT			_T("spot")

#define DOC_STATIS				_T("statis")
#define DOC_STATIS_GAXSET		_T("gax-set")
#define DOC_STATIS_XAXSET		_T("xax-set")
#define DOC_STATIS_YAXSET		_T("yax-set")
#define DOC_STATIS_GAX			_T("gax")
#define DOC_STATIS_XAX			_T("xax")
#define DOC_STATIS_YAX			_T("yax")

#define DOC_IMAGES				_T("img-list")
#define DOC_IMAGES_IMAGE		_T("img")

#define DOC_MEMO				_T("memo")
#define DOC_MEMO_LINE			_T("line")

#define DOC_RICH				_T("rich")
#define DOC_RICH_NODE			_T("node")
#define DOC_RICH_TITLE			_T("title")

#define DOC_TAG					_T("tag")
#define DOC_TAG_TEXT			_T("text")

#define DOC_CALENDAR			_T("calendar")

#define DOC_DIALOG				_T("dialog")
#define DOC_DIALOG_STATICBOX	_T("StaticBox")
#define DOC_DIALOG_EDITBOX		_T("EditBox")
#define DOC_DIALOG_LISTBOX		_T("ListBox")
#define DOC_DIALOG_NAVIBOX		_T("NaviBox")
#define DOC_DIALOG_SPINBOX		_T("SpinBox")
#define DOC_DIALOG_SLIDEBOX		_T("SlideBox")
#define DOC_DIALOG_RADIOBOX		_T("RadioBox")
#define DOC_DIALOG_CHECKBOX		_T("CheckBox")
#define DOC_DIALOG_DATEBOX		_T("DateBox")
#define DOC_DIALOG_TIMEBOX		_T("TimeBox")
#define DOC_DIALOG_SHAPEBOX		_T("ShapeBox")
#define DOC_DIALOG_PUSHBOX		_T("PushBox")
#define DOC_DIALOG_USERBOX		_T("UserBox")

#define DOC_EVENT				_T("event")
#define DOC_EVENT_ID			_T("ID")
#define DOC_EVENT_FROM			_T("From")
#define DOC_EVENT_SENDER		_T("Sender")
#define DOC_EVENT_SENDTIME		_T("SendTime")
#define DOC_EVENT_CODE			_T("Code")
#define DOC_EVENT_DESCRIBE		_T("Describe")
#define DOC_EVENT_MEDIUM		_T("Medium")
#define DOC_EVENT_CONTENT		_T("Content")
#define DOC_EVENT_TO			_T("To")
#define DOC_EVENT_RECEIPTOR		_T("Receiptor")
#define DOC_EVENT_RECEIPTTIME	_T("ReceiptTime")
#define DOC_EVENT_RECEIPTSTATE	_T("ReceiptState")

/**************************************property bag attributes***********************************/
#define PROPERTY_BAG_IDENTIFY		_T("Identify")
#define PROPERTY_BAG_POSITION		_T("Position")
#define PROPERTY_BAG_BEHAVE			_T("Behave")
#define PROPERTY_BAG_DATA			_T("Data")
#define PROPERTY_BAG_SOURCE			_T("Source")
#define PROPERTY_BAG_OTHER			_T("Other")

#define PROPERTY_BAG_PENSTYLE		_T("Pen")
#define PROPERTY_BAG_BRUSHSTYLE		_T("Brush")
#define PROPERTY_BAG_FONTSTYLE		_T("Font")
#define PROPERTY_BAG_TEXTSTYLE		_T("Text")
/****************************************document node attributes**********************************/
#define ATTR_CLASS					_T("class")
#define ATTR_NAME					_T("name")
#define ATTR_DATA					_T("data")
#define ATTR_TITLE					_T("title")
#define ATTR_STYLE					_T("style")
#define ATTR_CODE					_T("code")
#define ATTR_TYPE					_T("type")
#define ATTR_TIME					_T("time")
#define ATTR_TO						_T("to")
#define ATTR_FROM					_T("from")
#define ATTR_ID						_T("ID")
#define ATTR_ALTER					_T("alter")
#define ATTR_CONTENT				_T("content")
#define ATTR_DOCTYPE				_T("DOCTYPE")
#define ATTR_AUTHOR					_T("AUTHOR")
#define ATTR_COMPANY				_T("COMPANY")
#define ATTR_SCHEMA					_T("schema")
#define ATTR_CATEGORY				_T("category")
#define ATTR_SRC					_T("src")
#define ATTR_ALT					_T("alt")
#define ATTR_NOTES_TEXT				_T("text")
#define ATTR_NOTES_FILE				_T("file")

#define ATTR_DESCRIPTION			_T("Description")
#define ATTR_NEXTEXETIME			_T("NextExecuteTime")
#define ATTR_LASTEXETIME			_T("LastExecuteTime")
#define ATTR_TURNEDTO				_T("TurnedTo")
#define ATTR_EFFECTDATE				_T("EffectiveDate")
#define ATTR_EXPIRYDATE				_T("ExpiryDate")
#define ATTR_STARTTIME				_T("StartTime")
#define ATTR_INTERMONTHS			_T("IntervalMonths")
#define ATTR_INTERWEEKS				_T("IntervalWeeks")
#define ATTR_INTERDAYS				_T("IntervalDays")
#define ATTR_INTERHOURS				_T("IntervalHours")
#define ATTR_INTERMINUTES			_T("IntervalMinutes")
#define ATTR_INTERSECONDS			_T("IntervalSeconds")
#define ATTR_INTERCOUNTS			_T("IntervalCounts")

#define ATTR_FORMAT					_T("format")
#define ATTR_OPTIONS				_T("options")
#define ATTR_SOURCE					_T("source")
#define ATTR_MACRO					_T("macro")
#define ATTR_TABORDER				_T("taborder")
#define ATTR_GROUP					_T("group")
#define ATTR_IMAGE					_T("image")
#define ATTR_COLOR					_T("color")
#define ATTR_TRANSPARENT			_T("transparent")
#define ATTR_LEVEL					_T("level")
#define ATTR_CHECK					_T("check")

#define ATTR_TODAY					_T("today")
#define ATTR_EARLIEST				_T("earliest")
#define ATTR_LATEST					_T("latest")
#define ATTR_DAILY					_T("daily")
#define ATTR_DAILY_YEAR				_T("daily-year")
#define ATTR_DAILY_MONTH			_T("daily-month")
#define ATTR_DAILY_DAY				_T("daily-day")

#define ATTR_SHOWSUM				_T("show-sum")
#define ATTR_SHOWCHECK				_T("show-check")
#define ATTR_CLOCKWISE				_T("clockwise")
#define ATTR_STEPDRAW				_T("step-draw")

#define ATTR_ROWS					_T("rows")
#define ATTR_COLS					_T("cols")
#define ATTR_ROW					_T("row")
#define ATTR_COL					_T("col")
#define ATTR_MATRIX					_T("matrix")
#define ATTR_RX						_T("rx")
#define ATTR_RY						_T("ry")
#define ATTR_X						_T("x")
#define ATTR_Y						_T("y")
#define ATTR_WIDTH					_T("width")
#define ATTR_HEIGHT					_T("height")
#define ATTR_TITLE_WIDTH			_T("title-width")
#define ATTR_TITLE_HEIGHT			_T("title-height")
#define ATTR_ITEM_WIDTH				_T("item-width")
#define ATTR_ITEM_HEIGHT			_T("item-height")
#define ATTR_ITEM_SPAN				_T("item-span")
#define ATTR_ICON_SPAN				_T("icon-span")
#define ATTR_TEXT_INDENT			_T("text-indent")
#define ATTR_TEXT_PLACE				_T("text-place")
#define ATTR_ENTITY_HEIGHT			_T("entity-height")
#define ATTR_ENTITY_WIDTH			_T("entity-width")
#define ATTR_RATIO					_T("ratio")
#define ATTR_SPLITED				_T("splited")
#define ATTR_DYNAMIC				_T("dynamic")
#define ATTR_FIXED					_T("fixed")
#define ATTR_LINED					_T("lined")
#define ATTR_COORDINATE				_T("co-ordinate")
#define ATTR_SUBFIELD				_T("subfield")
#define ATTR_POINTS					_T("points")
#define ATTR_BASE					_T("base")
#define ATTR_SPAN					_T("span")

#define ATTR_COLBAR_HEIGHT			_T("colbar-height")
#define ATTR_ROWBAR_HEIGHT			_T("rowbar-height")
#define ATTR_ROWBAR_WIDTH			_T("rowbar-width")
#define ATTR_XAXBAR_HEIGHT			_T("xaxbar-height")
#define ATTR_XAXBAR_WIDTH			_T("xaxbar-width")
#define ATTR_YAXBAR_HEIGHT			_T("yaxbar-height")
#define ATTR_YAXBAR_WIDTH			_T("yaxbar-width")
#define ATTR_GAX_STEP				_T("step")
#define ATTR_GAX_MIDD				_T("midd")
#define ATTR_XAXIS					_T("xaxis")
#define ATTR_XAXDT					_T("xaxdt")
#define ATTR_XAXFMT					_T("xaxfmt")
#define ATTR_XAXWRP					_T("xaxwrp")

#define ATTR_STATIS_TYPE			_T("statis-type")
#define ATTR_STATIS_TYPE_OPTIONS	_T("line~Line;rect~Rect;pie~Pie;")
#define ATTR_STATIS_TYPE_LINE		_T("line")
#define ATTR_STATIS_TYPE_RECT		_T("rect")
#define ATTR_STATIS_TYPE_PIE		_T("pie")

#define ATTR_LINE_CAP				_T("line-cap")
#define ATTR_LINE_CAP_OPTIONS		_T("ellipse~Ellipse;rect~Rect;cross~Cross;star~Star;diamond~Diamond;")
#define ATTR_LINE_CAP_ELLIPSE		_T("ellipse")
#define ATTR_LINE_CAP_RECT			_T("rect")
#define ATTR_LINE_CAP_CROSS			_T("cross")
#define ATTR_LINE_CAP_STAR			_T("star")
#define ATTR_LINE_CAP_DIAMOND		_T("diamond")

#define ATTR_SHOW					_T("show")
#define ATTR_SHOW_OPTIONS			_T("image-only~ImageOnly;text-only~TextOnly;")
#define ATTR_SHOW_IMAGEONLY			_T("image-only")
#define ATTR_SHOW_TEXTONLY			_T("text-only")

#define ATTR_SHAPE					_T("shape")
#define ATTR_SHAPE_OPTIONS			_T("rect~Rect;round~Round;ellipse~Ellipse;brackets~Brackets;top-line~TopLine;bottom-line~BottomLine;left-line~LeftLine;right-line~RightLine;forward-slash~ForwardSlash;back-slash~BackSlash;multi-line~MultiLine;left-triangle~LeftTriangle;right-triangle~RightTriangle;top-triangle~TopTriangle;bottom-triangle~BottomTriangle;")
#define ATTR_SHAPE_RECT				_T("rect")
#define ATTR_SHAPE_ELLIPSE			_T("ellipse")
#define ATTR_SHAPE_ROUND			_T("round")
#define ATTR_SHAPE_BRACKETS			_T("brackets")
#define ATTR_SHAPE_TOPLINE			_T("top-line")
#define ATTR_SHAPE_BOTTOMLINE		_T("bottom-line")
#define ATTR_SHAPE_LEFTLINE			_T("left-line")
#define ATTR_SHAPE_RIGHTLINE		_T("right-line")
#define ATTR_SHAPE_FORWARDSLASH		_T("forward-slash")
#define ATTR_SHAPE_BACKSLASH		_T("back-slash")
#define ATTR_SHAPE_MULTILINE		_T("multi-line")
#define ATTR_SHAPE_TOPTRIANGLE			_T("top-triangle")
#define ATTR_SHAPE_BOTTOMTRIANGLE		_T("bottom-triangle")
#define ATTR_SHAPE_LEFTTRIANGLE			_T("left-triangle")
#define ATTR_SHAPE_RIGHTTRIANGLE		_T("right-triangle")

#define ATTR_ICONIC					_T("iconic")

#define ATTR_CODEBAR					_T("codebar")
#define ATTR_CODEBAR_OPTIONS			_T("CODE128~CODE128;PDF417~PDF417;QRCODE~QRCODE;")
#define ATTR_CODEBAR_CODE128			_T("CODE128")
#define ATTR_CODEBAR_PDF417				_T("PDF417")
#define ATTR_CODEBAR_QRCODE				_T("QRCODE")

#define ATTR_ANNO_TYPE				_T("type")
#define ATTR_ANNO_TYPE_ANCHOR		_T("ANCHOR")
#define ATTR_ANNO_TYPE_CIRCLE		_T("CIRCLE")
#define ATTR_ANNO_TYPE_TEXT			_T("TEXT")
#define ATTR_ANNO_TYPE_ICON			_T("ICON")
#define ATTR_ANNO_TYPE_RANGE		_T("RANGE")
#define ATTR_ANNO_TYPE_ANGLE		_T("ANGLE")

#define ATTR_SPOT_TYPE_OPTIONS		_T("text~Text;icon~Icon;color-bar~ColorBar;image~Image;")
#define ATTR_SPOT_TYPE_TEXT			_T("text")
#define ATTR_SPOT_TYPE_ICON			_T("icon")
#define ATTR_SPOT_TYPE_COLORBAR		_T("color-bar")
#define ATTR_SPOT_TYPE_IMAGE		_T("image")

#define ATTR_PLOT_TYPE				_T("plot-type")
#define ATTR_PLOT_TYPE_OPTIONS		_T("topoggram~TopogGram;contourgram~ContourGram;trendgram~TrendGram;scattergram~ScatterGram;pantogram~PantoGram;histogram~HistoGram;mediangram~MedianGram;bargram~BarGram;kpigram~KpiGram;radargram~RadarGram;fuelgram~FuelGram;taskgram~TaskGram;contragram~ContraGram;balancegram~BalanceGram;indicator~Indicator;thermometer~Thermometer;calendar~Calendar;")
#define ATTR_PLOT_TYPE_TOPOGGGRAM	_T("topoggram") //地形图
#define ATTR_PLOT_TYPE_CONTOURGRAM	_T("contourgram") //等高线
#define ATTR_PLOT_TYPE_TRENDGRAM	_T("trendgram") //趋势图
#define ATTR_PLOT_TYPE_SCATTERGRAM	_T("scattergram") //密度图
#define ATTR_PLOT_TYPE_PANTOGRAM	_T("pantogram") //比例图
#define ATTR_PLOT_TYPE_HISTOGRAM	_T("histogram") //直方图
#define ATTR_PLOT_TYPE_MEDIANGRAM	_T("mediangram") //中位图
#define ATTR_PLOT_TYPE_BARGRAM		_T("bargram") //条形图
#define ATTR_PLOT_TYPE_KPIGRAM		_T("kpigram") //达标图
#define ATTR_PLOT_TYPE_RADARGRAM	_T("radargram") //雷达图
#define ATTR_PLOT_TYPE_FUELGRAM		_T("fuelgram") //油量表
#define ATTR_PLOT_TYPE_TASKGRAM		_T("taskgram") //任务表
#define ATTR_PLOT_TYPE_CONTRAGRAM	_T("contragram") //对比图
#define ATTR_PLOT_TYPE_BALANCEGRAM	_T("balancegram") //平衡图
#define ATTR_PLOT_TYPE_INDICATOR	_T("indicator") //指示器
#define ATTR_PLOT_TYPE_THERMOMETER	_T("thermometer") //温度计
#define ATTR_PLOT_TYPE_CALENDAR		_T("calendar") //日历

#define ATTR_TEXT_TYPE					_T("text-type")
#define ATTR_TEXT_TYPE_TEXT				_T("text")
#define ATTR_TEXT_TYPE_WORDSTABLE		_T("words-table")
#define ATTR_TEXT_TYPE_STRINGTABLE		_T("string-table")
#define ATTR_TEXT_TYPE_IMAGE			_T("image")

#define ATTR_ICON					_T("icon")

#define ATTR_DATA_TYPE				_T("data-type")
#define ATTR_DATA_LEN				_T("data-len")
#define ATTR_DATA_DIG				_T("data-dig")
#define ATTR_DATA_MIN				_T("data-min")
#define ATTR_DATA_MAX				_T("data-max")

#define ATTR_DATA_TYPE_OPTIONS		_T("string~String;boolean~Boolean;integer~Integer;numeric~Numeric;date~Date;dateTime~DateTime;boolean~Boolean;binary~Binary;")
#define ATTR_DATA_TYPE_STRING		_T("string")
#define ATTR_DATA_TYPE_INTEGER		_T("integer")
#define ATTR_DATA_TYPE_NUMERIC		_T("numeric")
#define ATTR_DATA_TYPE_DATE			_T("date")
#define ATTR_DATA_TYPE_DATETIME		_T("dateTime")
#define ATTR_DATA_TYPE_BOOLEAN		_T("boolean")
#define ATTR_DATA_TYPE_BINARY		_T("binary")
#define ATTR_DATA_TYPE_COMPLEX		_T("complex")
#define ATTR_DATA_TYPE_STRING_ARRAY		_T("string-array")
#define ATTR_DATA_TYPE_NUMERIC_ARRAY	_T("numeric-array")
#define ATTR_DATA_TYPE_INTEGER_ARRAY	_T("integer-array")
#define ATTR_DATA_TYPE_BOOLEAN_ARRAY	_T("boolean-array")
#define ATTR_DATA_TYPE_DATE_ARRAY		_T("date-array")
#define ATTR_DATA_TYPE_TIME_ARRAY		_T("time-array")
#define ATTR_DATA_TYPE_DATETIME_ARRAY	_T("dateTime-array")
#define ATTR_DATA_TYPE_COMPLEX_ARRAY	_T("complex-array")
#define ATTR_DATA_TYPE_UNKNOWN			_T("unknown")

#define ATTR_PARAM_TYPE				_T("param-type")
#define ATTR_PARAM_TYPE_OPTIONS		_T("[in]~[in];[in,out]~[in,out];[out]~[out];")
#define ATTR_PARAM_TYPE_INPUT		_T("[in]")
#define ATTR_PARAM_TYPE_INPUTOUTPUT		_T("[in,out]")
#define ATTR_PARAM_TYPE_OUTPUT		_T("[out]")
#define ATTR_RETURN					_T("return")

#define ATTR_TABLE_NAME				_T("table-name")
#define ATTR_FIELD_NAME				_T("field-name")
#define ATTR_FIELD_TYPE				_T("field-type")
#define ATTR_FIELD_TYPE_OPTIONS		_T("prim-field~PrimField;data-field~DataField;calc-field~CalcField;")
#define ATTR_FIELD_CAST				_T("field-cast")
#define ATTR_FIELD_TYPE_DATA		_T("data-field")
#define ATTR_FIELD_TYPE_CALC		_T("calc-field")
#define ATTR_FIELD_TYPE_PRIM		_T("prim-field")
#define ATTR_UPDATEABLE				_T("updateable")
#define ATTR_UPDATE_TABLE			_T("update-table")
#define ATTR_LIMIT_CLAUSE			_T("limit-clause")
#define ATTR_FROM_CLAUSE			_T("from-clause")
#define ATTR_WHERE_CLAUSE			_T("where-clause")
#define ATTR_EXISTS_CLAUSE			_T("exists-clause")
#define ATTR_GROUP_CLAUSE			_T("group-clause")
#define ATTR_PRIMARY_KEY			_T("primary-key")

#define ATTR_SUM_MODE				_T("sum-mode")
#define ATTR_SUM_MODE_OPTIONS		_T("count~COUNT;sum~SUM;avg~AVG")
#define ATTR_SUM_MODE_COUNT			_T("count")
#define ATTR_SUM_MODE_SUM			_T("sum")
#define ATTR_SUM_MODE_AVG			_T("avg")

#define ATTR_CASE					_T("case")
#define ATTR_CASE_OPTIONS			_T("lower~Lower;upper~Upper;")
#define ATTR_CASE_LOWER				_T("lower")
#define ATTR_CASE_UPPER				_T("upper")

#define ATTR_VALUE					_T("value")

#define TF_OPTIONS					_T("1~True;0~False;")
#define TF_TRUE						_T("1")
#define TF_FALSE					_T("0")

#define ATTR_EDITOR					_T("editor")
#define ATTR_EDITOR_FIREEDIT		_T("fire-edit")
#define ATTR_EDITOR_FIRENUM			_T("fire-num")
#define ATTR_EDITOR_FIRELIST		_T("fire-list")
#define ATTR_EDITOR_FIREDATE		_T("fire-date")
#define ATTR_EDITOR_FIRETIME		_T("fire-time")
#define ATTR_EDITOR_FIREWORDS		_T("fire-words")
#define ATTR_EDITOR_FIRECHECK		_T("fire-check")
#define ATTR_EDITOR_FIREGRID		_T("fire-grid")
#define ATTR_EDITOR_RICHBOX			_T("rich-box")
#define ATTR_EDITOR_MEMOBOX			_T("memo-box")
#define ATTR_EDITOR_TAGBOX			_T("tag-box")
#define ATTR_EDITOR_TABLEBOX		_T("table-box")
#define ATTR_EDITOR_GRIDBOX			_T("grid-box")
#define ATTR_EDITOR_STATISBOX		_T("statis-box")
#define ATTR_EDITOR_FORMBOX			_T("form-box")
#define ATTR_EDITOR_OPTIONS			_T("fire-edit~FireEdit;fire-check~FireCheck;fire-num~FireNum;fire-list~FireList;fire-date~FireDate;fire-time~FireTime;fire-words~FireWords;fire-grid~FireGrid;")

#define ATTR_CONTROL				_T("control")
#define ATTR_CONTROL_RICHCTRL		_T("rich-ctrl")
#define ATTR_CONTROL_MEMOCTRL		_T("memo-ctrl")
#define ATTR_CONTROL_TAGCTRL		_T("tag-ctrl")
#define ATTR_CONTROL_GRIDCTRL		_T("grid-ctrl")
#define ATTR_CONTROL_STATISCTRL		_T("statis-ctrl")
#define ATTR_CONTROL_PHOTOCTRL		_T("photo-ctrl")
#define ATTR_CONTROL_IMAGESCTRL		_T("images-ctrl")
#define ATTR_CONTROL_TOPOGCTRL		_T("topog-ctrl")
#define ATTR_CONTROL_FORMCTRL		_T("form-ctrl")
#define ATTR_CONTROL_TREECTRL		_T("tree-ctrl")
#define ATTR_CONTROL_LISTCTRL		_T("list-ctrl")
#define ATTR_CONTROL_LABELCTRL		_T("label-ctrl")
#define ATTR_CONTROL_PROPERCTRL		_T("proper-ctrl")
#define ATTR_CONTROL_STATUSCTRL		_T("status-ctrl")
#define ATTR_CONTROL_TOOLCTRL		_T("tool-ctrl")
#define ATTR_CONTROL_TITLECTRL		_T("title-ctrl")
#define ATTR_CONTROL_TABLECTRL		_T("table-ctrl")
#define ATTR_CONTROL_NOTESCTRL		_T("notes-ctrl")
#define ATTR_CONTROL_OPTIONS		_T("rich-ctrl~RichCtrl;memo-ctrl~MemoCtrl;tag-ctrl~TagCtrl;grid-ctrl~GridCtrl;statis-ctrl~StatisCtrl;photo-ctrl~PhotoCtrl;images-ctrl~ImagesCtrl;topog-ctrl~TopogCtrl;form-ctrl~FormCtrl;tree-ctrl~TreeCtrl;list-ctrl~ListCtrl;label-ctrl~LabelCtrl;proper-ctrl~ProperCtrl;status-ctrl~StatusCtrl;tool-ctrl~ToolCtrl;title-ctrl~TitleCtrl;table-ctrl~TableCtrl;notes-ctrl~NotesCtrl;")

#define ATTR_EDITABLE				_T("editable")
#define ATTR_VISIBLE				_T("visible")
#define ATTR_PRINTABLE				_T("printable")
#define ATTR_NULLABLE				_T("nullable")
#define ATTR_SORTABLE				_T("sortable")
#define ATTR_GROUPABLE				_T("groupable")
#define ATTR_FIREABLE				_T("fireable")
#define ATTR_WRAPABLE				_T("wrapable")
#define ATTR_ZERONULL				_T("zeronull")

#define ATTR_ALIGNMENT				_T("alignment")
#define ATTR_ALIGNMENT_NEAR			_T("near")
#define ATTR_ALIGNMENT_FAR			_T("far")
#define ATTR_ALIGNMENT_CENTER		_T("center")
#define ATTR_ALIGNMENT_OPTIONS		_T("near~Near;center~Center;far~Far;")

#define ATTR_ORITATION				_T("oritation")
#define ATTR_ORITATION_LEFT			_T("left")
#define ATTR_ORITATION_RIGHT		_T("right")
#define ATTR_ORITATION_TOP			_T("top")
#define ATTR_ORITATION_BOTTOM		_T("bottom")

#define ATTR_LAYER					_T("layer")
#define ATTR_LAYER_HORZ				_T("horz")
#define ATTR_LAYER_VERT				_T("vert")
#define ATTR_LAYER_CROSS			_T("cross")
#define ATTR_LAYER_OPTIONS			_T("horz~Horz;vert~Vert;cross~Cross;")

#define ATTR_PRINTING				_T("printing")
#define ATTR_PRINTING_PORTRAIT		_T("portrait")
#define ATTR_PRINTING_LANDSCAPE		_T("landscape")
#define ATTR_PRINTING_OPTIONS		_T("portrait~Portrait;landscape~Landscape;")

#define ATTR_POSITION				_T("position")
#define ATTR_POSITION_LEFT			_T("left")
#define ATTR_POSITION_TOP			_T("top")
#define ATTR_POSITION_RIGHT			_T("right")
#define ATTR_POSITION_BOTTOM		_T("bottom")
#define ATTR_POSITION_LEFTTOP		_T("left-top")
#define ATTR_POSITION_RIGHTTOP		_T("right-top")
#define ATTR_POSITION_LEFTBOTTOM	_T("left-bottom")
#define ATTR_POSITION_RIGHTBOTTOM	_T("right-bottom")

#define ATTR_WRITETIME			_T("write-time")
#define ATTR_CREATETIME			_T("create-time")
#define ATTR_ACCESSTIME			_T("access-time")
#define ATTR_ARCHIVE			_T("archive")
#define ATTR_ETAG				_T("ETag")
#define ATTR_SIZE				_T("size")
#define ATTR_HIGH_SIZE			_T("high-size")
#define ATTR_LOW_SIZE			_T("low-size")

#define ATTR_ARCHIVE_H			_T("0")
#define ATTR_ARCHIVE_R			_T("1")
#define ATTR_ARCHIVE_W			_T("2")
#define ATTR_ARCHIVE_E			_T("4")

#endif

